name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  wrangler:
    name: wrangler
    runs-on: ubuntu-24.04-arm
    # Cache even on failure
    continue-on-error: true
    steps:
      - name: Deep checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --no-frozen-lockfile --prefer-offline

      - name: Build affected packages
        shell: bash
        run: pnpm --filter '...[main^]...' build

      - name: Deploy affected apps to Cloudflare
        run: pnpm --filter '...[main^]' wrangler:deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
